name: Deploy Vite App to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > jurist_quest.pem
          chmod 600 jurist_quest.pem

      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no -i jurist_quest.pem ubuntu@${{ secrets.EC2_HOST }} "echo '✅ SSH connection successful'"

      - name: Copy dist files to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/myapp"
          overwrite: true

      - name: Restart nginx
        run: ssh -o StrictHostKeyChecking=no -i jurist_quest.pem ubuntu@${{ secrets.EC2_HOST }} "sudo systemctl restart nginx"
